apiVersion: app/v1
kind: Deloyment
metadata:
  name: vproapp
  labels:
    app: vroapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vroapp
    template:
      metadata:
        labels:
          app:vproapp
      spec:
        containers:
          - name: vproapp
            image: vprofile/vprofileapp:V1
            ports:
              - name: vproapp-port
                containerPort: 8080
        initContainers:
          - name: init-mydb
            image: busybox
            command: ['sh','-c','util nslooup vrpodb; do echo waiting for mydb; sleep 2; done;']
          - name: init-memcache
            image: busybox
            command: ['sh','-c','util nslooup vrpodb; do echo waiting for mydb; sleep 2; done;']
